### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by sbasyrine** [KimMeen/SERIES#1]
Hello! I'm a master student and I'm working on predicting and forecasting the status of Ireland's charging stations given a time series dataset. What I need to do is to predict the status of  exactly three charging stations at a particular hour or period of time in the future (for example what would be the state of the charging station tomorrow at 8:00 am?)
If you could help me, it will mean a lot to me and I'll be so grateful.
Sincerely.

**Comment by KimMeen** [comment]
Hi, I found that you issued the same question [here](https://github.com/IcaroMourao/Multivariate-Time-Series-Forecasting/issues/1). 

As IcaroMourao said, you could specify your input variables (e.g., In my case, there are 15 of them) as the input sequence, and your output variables (what you are predicting for) as the output sequence. 

After this, you should go through with the **_seq2seq.py_** and **_step1-training.ipynb_** under my **_./demo_** folder. Please comment here if you have any questions :D

**Comment by sbasyrine** [comment]
Yes I sent the same message to several developers in order to get at least one answer.
Thank you so much.

**Comment by sbasyrine** [comment]
Hello,
I tried you code but I got many errors so I tried another model but I didn't know how to continue would you please help me out?

**Comment by sbasyrine** [comment]
This is my email sba.syrine@gmail.com

**Comment by KimMeen** [comment]
Hi, could you post some information about your errors?

**Comment by sbasyrine** [comment]
Hello,
First of all thank you so much for replying I was really struggling in this :'(
It was an error related to the training phase but I solved it :)
However I didn't continue with your model because I didn't get what exactly you're doing --'.
Okay I admit that I have no experience with time series and machine learning models but I tried to understand what you are developing and to be honest I'm still confused.
I really hope that if I'll explain my project goal to you, you'll tell me if it can be achieved by your model.
If you really have time and will to help me (I really hope that) I would like to chat with you using emails; this is mine sba.syrine@gmail.com (I've already sent you an email with it)
I'll be also so grateful because this is about master degree thesis and I'm still didn't progress :'(

**Comment by KimMeen** [comment]
Hi @sbasyrine, you may not found the datasets I used since I am not allowed to publish them here. However, you may get started from this dataset that I used in my demo: [pm2.5 dataset](https://github.com/KimMeen/SERIES/blob/master/playground/pm25.csv)

If you are going to do some kinds of multi-variables prediction in your project, then you should be definitely suitable to use [this repo](https://github.com/farizrahman4u/seq2seq) and get started to build your first demo! This keras-based implementation should be easier for you to read and implement your project 

I am currently busy but I am willing to know some specifications in your project! You can send it to me via my email if you're allowed to do it :)

**Comment by sbasyrine** [comment]
Thank you KimMeen, I sent you an email.
